# Generated by Django 3.0.3 on 2020-03-09 15:38

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('patron_checkin', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patron',
            name='_id',
            field=models.CharField(default=uuid.UUID('5da1c768-39d7-4cbd-9d49-19ce2b7ae346'), max_length=100, primary_key=True, serialize=False),
        ),
    ]
