# Generated by Django 3.0.3 on 2020-03-22 19:44

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('patron_checkin', '0005_auto_20200310_2024'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patron',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='patron',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='patron',
            name='other',
        ),
        migrations.AddField(
            model_name='patron',
            name='name',
            field=models.CharField(default='', max_length=127),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='patron',
            name='_id',
            field=models.CharField(default=uuid.UUID('ab15ab54-11d4-4fe2-90f3-e40ad5a32331'), max_length=127, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='patron',
            name='city',
            field=models.CharField(max_length=127, verbose_name='city became homeless'),
        ),
        migrations.AlterField(
            model_name='patron',
            name='gender',
            field=models.CharField(max_length=31),
        ),
        migrations.AlterField(
            model_name='patron',
            name='phone',
            field=models.CharField(max_length=31),
        ),
        migrations.AlterField(
            model_name='patron',
            name='reason',
            field=models.CharField(blank=True, max_length=127, null=True, verbose_name='reason in Rolla'),
        ),
        migrations.AlterField(
            model_name='patron',
            name='time_homeless',
            field=models.CharField(max_length=127),
        ),
    ]
