# Generated by Django 3.0.3 on 2020-03-22 19:55

from django.db import migrations, models
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('patron_checkin', '0006_auto_20200322_1444'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patron',
            name='time_homeless',
        ),
        migrations.AddField(
            model_name='patron',
            name='date_homeless',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='patron',
            name='_id',
            field=models.CharField(default=uuid.UUID('f41716b1-3e99-4096-ab82-821fb557ff87'), max_length=127, primary_key=True, serialize=False),
        ),
    ]
