# Generated by Django 3.0.3 on 2020-03-22 20:21

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('patron_checkin', '0007_auto_20200322_1455'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patron',
            name='_id',
            field=models.CharField(default=uuid.uuid4, max_length=127, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='patron',
            name='date_homeless',
            field=models.DateTimeField(verbose_name='date became homeless'),
        ),
    ]
