# Generated by Django 3.0.3 on 2020-04-07 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patron_checkin', '0008_auto_20200322_1521'),
    ]

    operations = [
        migrations.AddField(
            model_name='patron',
            name='date_profile_creation',
            field=models.DateField(auto_now_add=True, null=True, verbose_name='profile creation'),
        ),
    ]
