# Generated by Django 3.0.3 on 2020-04-08 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patron_checkin', '0009_patron_date_profile_creation'),
    ]

    operations = [
        migrations.AddField(
            model_name='patron',
            name='last_checkin',
            field=models.DateTimeField(blank=True, null=True, verbose_name='last checkin'),
        ),
        migrations.AlterField(
            model_name='patron',
            name='date_profile_creation',
            field=models.DateField(auto_now_add=True, null=True, verbose_name='date signed'),
        ),
    ]
