# Generated by Django 3.0.3 on 2020-04-18 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patron_checkin', '0010_auto_20200408_1021'),
    ]

    operations = [
        migrations.AddField(
            model_name='patron',
            name='notes',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
