# Generated by Django 3.0.3 on 2020-03-06 02:44

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('patron_checkin', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='patron',
            name='test_file',
            field=models.FileField(default=0, upload_to=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='patron',
            name='_id',
            field=models.CharField(default=uuid.UUID('f3f852fa-2034-4933-a9eb-cccb52cb4843'), max_length=100, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='patron',
            name='reason',
            field=models.CharField(max_length=20, verbose_name='reason in Rolla'),
        ),
    ]
