# Generated by Django 3.0.3 on 2020-03-06 02:44

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('patron_checkin', '0002_auto_20200305_2044'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patron',
            name='_id',
            field=models.CharField(default=uuid.UUID('e5904acc-1432-49f1-b632-fc9e0e7d3e0e'), max_length=100, primary_key=True, serialize=False),
        ),
    ]
