# Generated by Django 3.0.3 on 2020-03-10 00:14

from django.db import migrations, models
import rolla_mission.storage_backends
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('patron_checkin', '0002_auto_20200309_1038'),
    ]

    operations = [
        migrations.AddField(
            model_name='patron',
            name='signature',
            field=models.ImageField(blank=True, null=True, storage=rolla_mission.storage_backends.PrivateMediaStorage(), upload_to=''),
        ),
        migrations.AlterField(
            model_name='patron',
            name='_id',
            field=models.CharField(default=uuid.UUID('5f40ca99-b926-4faf-963c-de9d4543dc17'), max_length=100, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='patron',
            name='reason',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='reason in Rolla'),
        ),
    ]
