# Generated by Django 3.0.3 on 2020-03-06 02:45

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('patron_checkin', '0003_auto_20200305_2044'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patron',
            name='_id',
            field=models.CharField(default=uuid.UUID('0ed23b9c-092a-4147-b88b-275fe88915c8'), max_length=100, primary_key=True, serialize=False),
        ),
    ]
