# Generated by Django 3.0.3 on 2020-03-11 01:23

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('patron_checkin', '0003_auto_20200309_1914'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patron',
            name='_id',
            field=models.CharField(default=uuid.UUID('4c6a81e0-7957-4ce8-8a7c-4d370b759d76'), max_length=100, primary_key=True, serialize=False, verbose_name='id'),
        ),
        migrations.AlterField(
            model_name='patron',
            name='other',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='other reason'),
        ),
    ]
