# Generated by Django 3.0.3 on 2020-03-11 01:24

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('patron_checkin', '0004_auto_20200310_2023'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patron',
            name='_id',
            field=models.CharField(default=uuid.UUID('81828df0-f6c0-4ef3-b01d-5124034e7852'), max_length=100, primary_key=True, serialize=False),
        ),
    ]
