# Generated by Django 3.0.3 on 2020-03-06 02:45

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('patron_checkin', '0004_auto_20200305_2045'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patron',
            name='_id',
            field=models.CharField(default=uuid.UUID('ab7be280-fef2-48b0-83cb-6f2f9e9b00ba'), max_length=100, primary_key=True, serialize=False),
        ),
    ]
