# Generated by Django 3.0.3 on 2020-03-14 06:38

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('patron_checkin', '0005_auto_20200310_2024'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patron',
            name='_id',
            field=models.CharField(default=uuid.UUID('c476ed9b-e63d-4f51-af7b-8e072c543bf6'), max_length=100, primary_key=True, serialize=False),
        ),
    ]
