# Generated by Django 3.0.3 on 2020-03-21 16:37

from django.db import migrations, models
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('patron_checkin', '0005_auto_20200310_2024'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patron',
            name='time_homeless',
        ),
        migrations.AddField(
            model_name='patron',
            name='date_homeless',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='patron',
            name='_id',
            field=models.CharField(default=uuid.UUID('87419f96-1c4a-4023-9301-212f57d4c8cf'), max_length=100, primary_key=True, serialize=False),
        ),
    ]
