# Generated by Django 3.0.3 on 2020-03-06 02:53

from django.db import migrations, models
import rolla_mission.storage_backends
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('patron_checkin', '0006_auto_20200305_2045'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patron',
            name='_id',
            field=models.CharField(default=uuid.UUID('e93a2d46-4fdd-49ad-bc5a-9a36dff5d7aa'), max_length=100, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='patron',
            name='test_file',
            field=models.FileField(storage=rolla_mission.storage_backends.PrivateMediaStorage(), upload_to=''),
        ),
    ]
