# Generated by Django 3.0.3 on 2020-03-06 03:02

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('patron_checkin', '0007_auto_20200305_2053'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patron',
            name='test_file',
        ),
        migrations.AlterField(
            model_name='patron',
            name='_id',
            field=models.CharField(default=uuid.UUID('56c1e957-ebbe-4687-8627-3db5c927db78'), max_length=100, primary_key=True, serialize=False),
        ),
    ]
