# Generated by Django 3.0.3 on 2020-03-19 04:50

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('patron_checkin', '0007_auto_20200316_2205'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patron',
            name='_id',
            field=models.CharField(default=uuid.UUID('e09643be-77e4-4369-83cc-6ce203c89c01'), max_length=100, primary_key=True, serialize=False),
        ),
    ]
