# Generated by Django 3.0.3 on 2020-03-19 06:36

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('patron_checkin', '0008_auto_20200318_2350'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patron',
            name='_id',
            field=models.CharField(default=uuid.UUID('9cbc89d0-2af5-4eee-8566-7284804f9d9c'), max_length=100, primary_key=True, serialize=False),
        ),
    ]
