# Generated by Django 3.0.3 on 2020-03-19 06:45

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('patron_checkin', '0010_auto_20200319_0142'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patron',
            name='_id',
            field=models.CharField(default=uuid.UUID('fcd157e4-0f42-4307-8b45-322a020b3d80'), max_length=100, primary_key=True, serialize=False),
        ),
    ]
