# Generated by Django 3.0.3 on 2020-03-19 06:47

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('patron_checkin', '0011_auto_20200319_0145'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patron',
            name='_id',
            field=models.CharField(default=uuid.UUID('7486bb75-7a5b-40a6-afab-a7e11159b666'), max_length=100, primary_key=True, serialize=False),
        ),
    ]
